CREATE TABLE IF NOT EXISTS midi (
	id serial primary key,
    dispNum3 varchar(20) NOT NULL,
    incidNum3 varchar(20) NOT NULL,
    dispNum4 varchar(20) NOT NULL,
    incidNum4 varchar(20) NOT NULL,
    st_day int default null,
    st_month int default null,
    st_year int default null,
    end_day int default null,
    end_month int default null,
    end_year int default null,
    duration int default null,
    tbi int default null,
    fatality int default null,
    fatalPre int default null,
    action int default null,
    hostlev int default null,
    numA int default null,
    revtyp1 int default null,
    revtyp2 int default null,
    version varchar(10) default null
    );

COPY midi 
(dispNum3,
    incidNum3,
    dispNum4,
    incidNum4,
    st_day,
    st_month,
    st_year,
    end_day,
    end_month,
    end_year,
    duration,
    tbi,
    fatality,
    fatalPre,
    action,
    hostlev,
    numA,
    revtyp1,
    revtyp2,
    version)
FROM '/home/bauer/midData/MIDI_4.01.csv' DELIMITER ',' CSV HEADER;


CREATE TABLE IF NOT EXISTS midip (
    id serial primary key,
    dispNum3 varchar(20) NOT NULL,
    incidNum3 varchar(20) NOT NULL,
    dispNum4 varchar(20) NOT NULL,
    incidNum4 varchar(20) NOT NULL,
    stAbb varchar(20) default null,
    ccode varchar(20) default null,
    st_day int default null,
    st_month int default null,
    st_year int default null,
    end_day int default null,
    end_month int default null,
    end_year int default null,
    inSideA int default null,
    sideA int default null,
    fatality int default null,
    fatalPre int default null,
    action int default null,
    hostlev int default null,
    numA int default null,
    revtyp1 int default null,
    revtyp2 int default null,
    version varchar(10) default null
    );

COPY midip 
(dispNum3,
    incidNum3,
    dispNum4,
    incidNum4,
    stAbb,
    ccode,
    st_day,
    st_month,
    st_year,
    end_day,
    end_month,
    end_year,
    inSideA,
    sideA,
    fatality,
    fatalPre,
    action,
    hostlev,
    revtyp1,
    revtyp2,
    version)
FROM '/home/bauer/midData/MIDIP_4.01.csv' DELIMITER ',' CSV HEADER;
