CREATE TABLE IF NOT EXISTS midDyadic (
	id serial primary key,
    DispNum varchar(20) NOT NULL,
    DyMIDNum varchar(20) NOT NULL,
    ccode1 varchar(20) NOT NULL,
    ccode2 varchar(20) not null,
    dyad_st_day int default null,
    dyad_st_month int default null,
    dyad_st_year int default null,
    dyad_end_day int default null,
    dyad_end_month int default null,
    dyad_end_year int default null,
    hiactA int default null,
    hiactB int default null,
    hostlevA int default null,
    hostlevB int default null,
    sideAA int default null,
    sideAB int default null,
    revstatA int default null,
    revtyp1A int default null,
    revtyp2A int default null,
    revstatB int default null,
    revtyp1B int default null,
    revtyp2B int default null,
    origA int default null,
    origB int default null,
    fatalA int default null,
    fatalB int default null,
    fatalPrA int default null,
    fatalPrB int default null,
    roleA int default null,
    roleB int default null,
    reciproc int default null,
    sideADyA int default null,
    sideADyB int default null,
    version varchar(10) default null
    );

COPY midDyadic 
(DispNum,
    DyMIDNum,
    ccode1,
    ccode2,
    dyad_st_day,
    dyad_st_month,
    dyad_st_year,
    dyad_end_day,
    dyad_end_month,
    dyad_end_year,
    hiactA,
    hiactB,
    hostlevA,
    hostlevB,
    sideAA,
    sideAB,
    revstatA,
    revtyp1A,
    revtyp2A,
    revstatB,
    revtyp1B,
    revtyp2B,
    origA,
    origB,
    fatalA,
    fatalB,
    fatalPrA,
    fatalPrB,
    roleA,
    roleB,
    reciproc,
    sideADyA,
    sideADyB,
    version)
FROM '/home/bauer/midData/MIDDyadic_v3.10.csv' DELIMITER ',' CSV HEADER;
